package dev.pompilius

import scala.util.matching.Regex

object Strings {
  // Cabecera de Nginx
  val N_IPCOUNTRY = "N-IpCountry"

  // Cabecera para Auth alternativas
  val X_User_Id = "X-User-Id"
  val X_Session_Id = "X-Session-Id"

  //Constantes
  val local = "local"
  val dev = "dev"

  //Propiedades y parámetros
  val address = "address"
  val antecedents = "antecedents"
  val area = "area"
  val authors = "authors"
  val available = "available"
  val availableLanguages = "availableLanguages"
  val avatar = "avatar"
  val barterId = "barterId"
  val baseUrl = "baseUrl"
  val bio = "bio"
  val buyerId = "buyerId"
  val closeAllSessions = "closeAllSessions"
  val code = "code"
  val cancelledAt = "cancelledAt"
  val completedAt = "completedAt"
  val collectionMethods = "collectionMethods"
  val contentType = "contentType"
  val coordinates = "coordinates"
  val country = "country"
  val countryOverride = "countryOverride"
  val created = "created"
  val createdAt = "createdAt"
  val currentDateTime = "currentDateTime"
  val debugId = "debugId"
  val deleted = "deleted"
  val description = "description"
  val email = "email"
  val enabled = "enabled"
  val endDate = "endDate"
  val environment = "environment"
  val error = "error"
  val file = "file"
  val filename = "filename"
  val fingerprint = "fingerprint"
  val firstName = "firstName"
  val fullName = "fullName"
  val geologicalProcesses = "geologicalProcesses"
  val id = "id"
  val isFresh = "isFresh"
  val isPublic = "isPublic"
  val language = "language"
  val lastName = "lastName"
  val limit = "limit"
  val localization = "localization"
  val logAllExceptions = "logAllExceptions"
  val logAllRequests = "logAllRequests"
  val mailSent = "mailSent"
  val mailType = "mailType"
  val materialsUsed = "materialsUsed"
  val metadata = "metadata"
  val methods = "methods"
  val minerals = "minerals"
  val name = "name"
  val nameSection = "nameSection"
  val newPassword = "newPassword"
  val node = "node"
  val nodeId = "nodeId"
  val notes = "notes"
  val observations = "observations"
  val offeredResource = "offeredResource"
  val offeredResourceId = "offeredResourceId"
  val offset: String = "offset"
  val oldPassword = "oldPassword"
  val orderBy = "orderBy"
  val parameters = "parameters"
  val password = "password"
  val phone = "phone"
  val rejectedAt = "rejectedAt"
  val relativePath = "relativePath"
  val requestedResourceId = "requestedResourceId"
  val resourceId = "resourceId"
  val resourceType = "resourceType"
  val role = "role"
  val roles = "roles"
  val rockType = "rockType"
  val sample = "sample"
  val sampleData = "sampleData"
  val sampleId = "sampleId"
  val sampleIds = "sampleIds"
  val sampleType = "sampleType"
  val search = "search"
  val section = "section"
  val sentAt = "sentAt"
  val sellerId = "sellerId"
  val sessionId = "sessionId"
  val size = "size"
  val startDate = "startDate"
  val study = "study"
  val studyId = "studyId"
  val studyData = "studyData"
  val summary = "summary"
  val token = "token"
  val transactionId = "transactionId"
  val transactionStatus = "transactionStatus"
  val transactionType = "transactionType"
  val updated = "updated"
  val updatedAt = "updatedAt"
  val uploadURL = "uploadUrl"
  val user = "user"
  val userId = "userId"
  val username = "username"
  val useSSL = "useSSL"
  val valid = "valid"
  val variants = "variants"
  val visibility = "visibility"

  val signedTokenRegex: Regex = """^(e[A-Za-z0-9\-_]+\.[A-Za-z0-9\-_]+)$""".r
  val usernameRegex: Regex = """^([a-zA-Z0-9\_]+)$""".r
  val urlSafeRegex: Regex = """^([\p{L}0-9-._~]+)$""".r
  val emailRegex: Regex = """^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$""".r
}
