include "application.conf"

logAllExceptions = true
useSSL = true

play {
  http {
    session = {
      secure = true,
      sameSite = "None",
    }
  }
}

countries {
  allowCountryOverride = true
}

eagerSingletons {
  enabled = []
}

emails {
  domains {
    blacklist = "https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/master/disposable_email_blocklist.conf"
  }
}

//Mirar esto
auth {
  resetPasswordUrl = "https://pompilius.dev/password/reset"
}

