include "application.conf"

logAllExceptions = false
useSSL = true

play {
  http {
    session = {
      secure = true,
      sameSite = "None",
    }
  }
}

scalikejdbc.global {
  loggingSQLAndTime.warningThresholdMillis = 500
}

countries {
  allowCountryOverride = true
}

emails {
  domains {
    blacklist = "https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/master/disposable_email_blocklist.conf"
  }
}

sendgrid {
  enabled = true
}

//Mirar esto
auth {
  resetPasswordUrl = "https://pompilius.dev/password/reset"
}