services:
  mysql:
    image: mysql:8
    container_name: pompiliusdb
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - pompilius-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 5

  backend:
    image: ghcr.io/jai1234daw/pompilius:latest
    container_name: pompiliusbackend
    environment:
      ENVIRONMENT: "docker"
      BASE_URL: ${BASE_URL}
      USE_SSL: ${USE_SSL}
      NODE_ID: ${NODE_ID}

      SECRET_KEY: ${SECRET_KEY}

      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      JDBC_DATABASE_USERNAME: ${JDBC_DATABASE_USERNAME}
      JDBC_DATABASE_PASSWORD: ${JDBC_DATABASE_PASSWORD}

      RESET_PASSWORD_URL: ${RESET_PASSWORD_URL}
      PURCHASE_RESOURCE_URL: ${PURCHASE_RESOURCE_URL}

      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

      MAIL_TOKEN_SECRET_KEY: ${MAIL_TOKEN_SECRET_KEY}
      USERNAME_MAIL: ${USERNAME_MAIL}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      PAYMENT_COMPLETED_URL: ${PAYMENT_COMPLETED_URL}
      PAYMENT_CANCELED_URL: ${PAYMENT_CANCELED_URL}
      BASE_URL_APP_DEPLOYMENT: ${BASE_URL_APP_DEPLOYMENT}
    ports:
      - 9000:9000
    volumes:
      - pompilius-data:/root/tmp/strataShare/attachments
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: ghcr.io/jai1234daw/nautilus:latest
    ports:
      - 80:80
    environment:
      BACKEND_URL: ${BACKEND_URL}
      API_URL: ${API_URL}
    depends_on:
      - backend
volumes:
  pompilius-data:
  pompilius-db: